app = "n8n-chatbot"
primary_region = "dfw" # choose nearest region (e.g., mia, iad, gru, sjc)

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
