app = "n8n-chatbot"
primary_region = "dfw"  # Dallas, Texas (US)

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_HOST = "n8n-chatbot-6ixegw.fly.dev"
  N8N_PORT = 443
  N8N_PROTOCOL = "https"
  WEBHOOK_URL = "https://n8n-chatbot-6ixegw.fly.dev/webhook/e8380a2c-fc3c-4f82-9cab-3598f0ded2b1/chat"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
